import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ahh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <script
          src='https://kit.fontawesome.com/0b55ba9d36.js'
          crossorigin='anonymous'
        ></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
